# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
##########################################################################
FROM gcr.io/oss-fuzz-base/base-builder-jvm
#RUN curl -L %s -o ant.zip && unzip ant.zip -d $SRC/ant && rm -rf ant.zip
#RUN curl -L %s -o protoc.zip && mkdir -p $SRC/protoc && unzip protoc.zip -d $SRC/protoc && rm -rf protoc.zip
RUN curl -L %s -o jdk.tar.gz && tar zxf jdk.tar.gz && rm -rf jdk.tar.gz
COPY ant.zip $SRC/ant.zip
COPY protoc.zip $SRC/protoc.zip
RUN unzip ant.zip -d $SRC/ant && rm ./ant.zip
RUN mkdir -p $SRC/protoc
RUN unzip protoc.zip -d $SRC/protoc && rm ./protoc.zip
ENV ANT $SRC/ant/apache-ant-1.10.13/bin/ant
ENV JAVA_HOME="$SRC/%s"
ENV PATH="$JAVA_HOME/bin:$SRC/protoc/bin:$PATH"
#RUN git clone --depth 1 %s %s
COPY %s %s
COPY *.sh *.java $SRC/
%sRUN mkdir -p $SRC/build_jar
%sCOPY build-jar/*.jar $SRC/build_jar/
WORKDIR $SRC/%s
