# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
##########################################################################
FROM gcr.io/oss-fuzz-base/base-builder-python

RUN pip3 install --upgrade pip && pip3 install cython

RUN rm -rf /fuzz-introspector/tools/auto-fuzz/fuzzer_generator
RUN rm -rf /fuzz-introspector/tools/auto-fuzz/objects
RUN echo "[]" > $OUT/possible_targets
COPY fuzzer_generator /fuzz-introspector/tools/auto-fuzz/fuzzer_generator
COPY objects /fuzz-introspector/tools/auto-fuzz/objects
COPY constants.py /fuzz-introspector/tools/auto-fuzz
COPY work $SRC/work
COPY build.py /fuzz-introspector/tools/auto-fuzz/fuzzer_generator/

RUN cd /fuzz-introspector && \
    pip3 install -r ./requirements.txt && \
    echo "python3 /fuzz-introspector/tools/auto-fuzz/fuzzer_generator/build.py" > $SRC/build.sh

WORKDIR /fuzz-introspector/tools/auto-fuzz/fuzzer_generator
